export const LOGIN_URL = '/oauth2/authorization/google';
export const MIN_CONTRACT_DEPOSIT = 10; // tokens
export const MIN_BALANCE = 0.0087;
export const MAX_CONTRACT_PROPERTIES_COUNT = 9;
export const RINKEBY_NETWORK = 'https://rinkeby.infura.io/DUsjLle6DbxbPVvJFDhL';
export const MAIN_NETWORK = 'https://mainnet.infura.io/5VkzsA31kYsWyrqC9GCT';
export const LOCAL_NETWORK = 'https://localhost:8545';
export const SCAFFOLDS_LIMIT = 10;
export const GATEWAY_LIMIT = 10;
export const TRANSACTIONS_LIMIT = 10;
