export const FETCH_KEYS = 'FETCH_KEYS';

export const SET_AUTH = 'SET_AUTH';
export const FETCH_USER = 'FETCH_USER';
export const SET_WALLET_METHOD = 'SET_WALLET_METHOD';
export const SET_CURRENT_ETH_ACCOUNT = 'SET_CURRENT_ETH_ACCOUNT';

export const SET_GLOBAL_PROPERTIES = 'SET_GLOBAL_PROPERTIES';

export const SET_ETHEREUM_SCAFFOLD_TEMPLATES = 'SET_ETHEREUM_SCAFFOLD_TEMPLATES';

export const CONVERT_CURRENCIES = 'CONVERT_CURRENCIES';

export const FETCH_OPEN_SCAFFOLDS = 'FETCH_OPEN_SCAFFOLDS';

export const FETCH_ETHEREUM_SCAFFOLDS = 'FETCH_ETHEREUM_SCAFFOLDS';
export const SET_ETHEREUM_SCAFFOLD_SET = 'SET_ETHEREUM_SCAFFOLD_SET';
export const SET_ETHEREUM_SCAFFOLD_SHARE_HOLDERS = 'SET_ETHEREUM_SCAFFOLD_SHARE_HOLDERS';
export const SET_ETHEREUM_SCAFFOLD_TRANSACTIONS = 'SET_ETHEREUM_SCAFFOLD_TRANSACTIONS';
export const UPDATE_ETHEREUM_SCAFFOLD_TRANSACTIONS = 'UPDATE_ETHEREUM_SCAFFOLD_TRANSACTIONS';
export const ADD_MORE_ETHEREUM_SCAFFOLD_TRANSACTIONS = 'ADD_MORE_ETHEREUM_SCAFFOLD_TRANSACTIONS';

export const GET_ETHEREUM_SCAFFOLD_FIELDS = 'GET_ETHEREUM_SCAFFOLD_FIELDS';
export const LOAD_ETHEREUM_SCAFFOLD_FIELDS = 'LOAD_ETHEREUM_SCAFFOLD_FIELDS';

export const UPDATE_CURRENT_ETHEREUM_SCAFFOLD_INSTANCE = 'UPDATE_CURRENT_ETHEREUM_SCAFFOLD_INSTANCE';

export const SET_DEV_SHARES = 'SET_DEV_SHARES';

export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_WITHDRAWAL_MODAL = 'SHOW_WITHDRAWAL_MODAL';

export const FETCH_GATEWAY_APPLICATIONS = 'FETCH_GATEWAY_APPLICATIONS';
export const SET_GATEWAY_APPLICATION_SET = 'SET_GATEWAY_APPLICATION_SET';
export const FETCH_GATEWAY_APPLICATION_WALLET = 'FETCH_GATEWAY_APPLICATION_WALLET';

export const FETCH_USER_TOKENS = 'FETCH_USER_TOKENS';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
