export const FETCH_KEYS = 'FETCH_KEYS';

export const SET_AUTH = 'SET_AUTH';
export const FETCH_USER = 'FETCH_USER';
export const SET_WALLET_METHOD = 'SET_WALLET_METHOD';
export const SET_CURRENT_ETH_ACCOUNT = 'SET_CURRENT_ETH_ACCOUNT';

export const SET_GLOBAL_PROPERTIES = 'SET_GLOBAL_PROPERTIES';

export const SET_SCAFFOLD_TEMPLATES = 'SET_SCAFFOLD_TEMPLATES';

export const CONVERT_CURRENCIES = 'CONVERT_CURRENCIES';

export const FETCH_SCAFFOLDS = 'FETCH_SCAFFOLDS';
export const SET_SCAFFOLD_SET = 'SET_SCAFFOLD_SET';
export const SET_SCAFFOLD_SHARE_HOLDERS = 'SET_SCAFFOLD_SHARE_HOLDERS';
export const SET_SCAFFOLD_TRANSACTIONS = 'SET_SCAFFOLD_TRANSACTIONS';
export const UPDATE_SCAFFOLD_TRANSACTIONS = 'UPDATE_SCAFFOLD_TRANSACTIONS';
export const ADD_MORE_SCAFFOLD_TRANSACTIONS = 'ADD_MORE_SCAFFOLD_TRANSACTIONS';

export const GET_SCAFFOLD_FIELDS = 'GET_SCAFFOLD_FIELDS';
export const LOAD_SCAFFOLD_FIELDS = 'LOAD_SCAFFOLD_FIELDS';

export const FETCH_ONCHAIN_SCAFFOLD_SUMMARY = 'FETCH_ONCHAIN_SCAFFOLD_SUMMARY';
export const UPDATE_CURRENT_SCAFFOLD_INSTANCE = 'UPDATE_CURRENT_SCAFFOLD_INSTANCE';

export const SET_DEV_SHARES = 'SET_DEV_SHARES';

export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_WITHDRAWAL_MODAL = 'SHOW_WITHDRAWAL_MODAL';
