CREATE TABLE users(
  id BIGSERIAL PRIMARY KEY,
  google_id VARCHAR UNIQUE NOT NULL,
  public_key VARCHAR UNIQUE NOT NULL,
  credits INT NOT NULL
);

CREATE TABLE scaffolds(
  id BIGSERIAL PRIMARY KEY,
  address VARCHAR UNIQUE NOT NULL,
  user_id BIGINT REFERENCES users,
  abi VARCHAR NOT NULL
);