CREATE TABLE roles(
  id BIGSERIAL PRIMARY KEY,
  key VARCHAR NOT NULL UNIQUE
);

INSERT INTO roles(key) VALUES ('ROLE_DEPLOY');

CREATE TABLE users2roles(
  user_id BIGINT NOT NULL REFERENCES users,
  role_id BIGINT NOT NULL REFERENCES roles
);